default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # General pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Commit linting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, chore]

  # Python linting
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff Lint & Auto-fix
        entry: ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff Format
        entry: ruff format
        language: system
        types: [python]

  # Secrets detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        args: [--staged, --verbose]

  # Docstrings testing
  - repo: local
    hooks:
      - id: doctests
        name: Doctests
        entry: pytest --doctest-modules -q
        language: system
        types: [python]
